# Values to apply in Dev Environment

name: "sample-app"
nameOverride: "sample-app"

image:
  tag: "1.0.1-20220322-153847-4d06f31"

# Config
config:
  env:
    APP_ENVIRONMENT: dev
    CHAOS_READINESS_ENABLE: "false"
    CHAOS_READINESS_CRON: "0 */2 * * * ?"
    CHAOS_LIVENESS_ENABLE: "false"
    CHAOS_LIVENESS_CRON: "0 */2 * * * ?"

# Secrets
secrets:
  env: 
    APP_ENVIRONMENT_SECRET: my-dev-secret
