---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: gitops-monorepo-cicd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.operator: apiKey, login
  accounts.developer: apiKey, login
