---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: gitops-monorepo-cicd
  labels:
    component-family: tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-monorepo-tools
  source:
    repoURL: https://github.com/rmarting/gitops-monorepo-sample.git
    targetRevision: HEAD
    path: charts/pipelines-chart
    helm:
      valueFiles:
        - ../../argocd/tools/pipelines/values.yaml
  destination:
    namespace: gitops-monorepo-cicd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
