apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: gitops-monorepo-cicd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: gitops-monorepo-tools
  source:
    repoURL: https://github.com/rmarting/gitops-monorepo-sample.git
    targetRevision: HEAD
    path: charts/pipelines-chart
    helm:
      values: |-
        git:
          user: TO_BE_DEFINED
          token: TO_BE_DEFINED
  destination:
    namespace: gitops-monorepo-cicd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
