# Values to apply in Production Environment

name: "sample-app"
nameOverride: "sample-app"

# Application Deployment

replicaCount: 1

image:
  tag: "1.0.3-20220314-193449-cbd3d86"

# Config
config:
  env:
    APP_ENVIRONMENT: pro
    CHAOS_READINESS_ENABLE: "false"
    CHAOS_READINESS_CRON: "0 */2 * * * ?"
    CHAOS_LIVENESS_ENABLE: "false"
    CHAOS_LIVENESS_CRON: "0 */2 * * * ?"

# Secrets
secrets:
  env: 
    APP_ENVIRONMENT_SECRET: my-pro-secret
