# Values to apply in Integration Environment

name: "sample-frontend"
nameOverride: "sample-frontend"

# Application Deployment

replicaCount: 1

image:
  tag: "1.0.0-2022-03-24-13-19-04"

# Config
config:
  enabled: true
  values:
    backendServiceUrl: http://sample-backend-gitops-monorepo-tst.apps.labs.sandbox893.opentlc.com
    environment: tst

# Route
route:
  secure:
    enabled: false
