# Values to apply in Integration Environment

name: "sample-frontend"
nameOverride: "sample-frontend"

# Application Deployment

replicaCount: 1

image:
  tag: "0.0.0-2022-03-24-11-42-56"

# Config
config:
  enabled: true
  values:
    backendServiceUrl: https://sample-backend-gitops-monorepo-tst.apps.labs.sandbox893.opentlc.com
    environment: tst
