---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-monorepo-apps
  namespace: gitops-monorepo-cicd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "GitOps Product MonoRepo Project - Apps"
  destinations:
    - namespace: gitops-monorepo-dev
      server: https://kubernetes.default.svc
    - namespace: gitops-monorepo-tst
      server: https://kubernetes.default.svc
    - namespace: gitops-monorepo-pro
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/rmarting/gitops-monorepo-sample.git
