apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-backend-tst
  namespace: gitops-monorepo-cicd
  labels:
    component-family: application
    component-type: backend
    environment-type: tst
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: gitops-monorepo-apps
  source:
    repoURL: https://github.com/rmarting/gitops-monorepo-sample.git
    targetRevision: HEAD
    path: charts/quarkus-app-chart
    helm:
      valueFiles:
        - ../../argocd/applications/sample-backend/tst/values.yaml
  destination:
    namespace: gitops-monorepo-tst
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
