# Values to apply in Integration Environment

name: "sample-backend"
nameOverride: "sample-backend"

# Application Deployment

replicaCount: 1

image:
  tag: "1.0.1-20220324-193233-6e3819d"

# Config
config:
  env:
    APP_ENVIRONMENT: "int"
    CHAOS_READINESS_ENABLE: "false"
    CHAOS_READINESS_CRON: "0 */2 * * * ?"
    CHAOS_LIVENESS_ENABLE: "false"
    CHAOS_LIVENESS_CRON: "0 */2 * * * ?"

# Secrets
secrets:
  env: 
    APP_ENVIRONMENT_SECRET: my-int-secret

# Route
route:
  secure:
    enabled: false
