{{- range $key := .Values.git.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-cli-auth-{{ .name }}
spec:
  encryptedData:
    .gitconfig: {{ .data.config }}
    .git-credentials: {{ .data.credentials  }}
  template:
    metadata:
      {{- if .annotations }}
      annotations: 
        {{- .annotations | toYaml | nindent 8 }}
      {{- end}}
      {{- if .labels }}
      labels:
        {{- .labels | toYaml | nindent 8 }}
      {{- end}}
      name: git-cli-auth-{{ .name }}
    type: {{ .type | default "Opaque" | quote }}
{{- end }}
