---
kind: Secret
apiVersion: v1
metadata:
  name: git-cli-auth
type: Opaque
stringData:
  .gitconfig: |
    [http]
      sslVerify = false
    [credential "{{ .Values.git.full_url }}"]
      helper = store
  .git-credentials: |
    https://{{ .Values.git.user }}:{{ .Values.git.token }}@{{ .Values.git.base_url }}
