---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-cli-auth
spec:
  template:
    metadata:
      name: git-cli-auth
    type: Opaque
  encryptedData:
    .gitconfig: {{ .Values.git.sealed_secret.config | quote }}
    .git-credentials: {{ .Values.git.sealed_secret.credentials | quote }}
