# Values to apply in Integration Environment

name: "sample-app"
nameOverride: "sample-app"

# Application Deployment

replicaCount: 2

image:
  tag: "1.0.2-20220310-150002-47a046e"

# Config
# Config
config:
  env:
    APP_ENVIRONMENT: int

# Secrets
secrets:
  env: 
    APP_ENVIRONMENT_SECRET: my-int-secret
