apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  description: >-
    This task can be used to run npm goals on a project.

    This task can be used to run npm goals on a project
    where package.json is present and has some pre-defined
    npm scripts.
  workspaces:
    - name: source
  params:
    - name: PATH_CONTEXT
      type: string
      default: "."
      description: The path where package.json of the project is defined.
    - name: SCRIPT
      type: string
      description: The npm script to run
    - name: IMAGE
      type: string
      default: "docker.io/library/node:12-alpine@sha256:dfbebf17bfb014e1e7068e76325a117bccf8679c68aec6a28514184a209c8bae"
      description: The node image you want to use.
  results:
    - name: APP_VERSION
      description: Application version from package.json, added the timestamp.
  steps:
    - name: npm-script
      image: $(params.IMAGE)
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      script: |
        #!/usr/bin/env sh
        $(params.SCRIPT)      
      env:
        - name: CI
          value: "true"

    - name: npm-get-version
      image: bash:latest
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)      
      script: |
        echo -n $(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g') | tee $(results.APP_VERSION.path)
