# Values to apply in Dev Environment

name: "sample-frontend"
nameOverride: "sample-frontend"

image:
  tag: "latest"

# Config
config:
  env:
    APP_ENVIRONMENT: dev
    CHAOS_READINESS_ENABLE: "false"
    CHAOS_READINESS_CRON: "0 */2 * * * ?"
    CHAOS_LIVENESS_ENABLE: "false"
    CHAOS_LIVENESS_CRON: "0 */2 * * * ?"

# Secrets
secrets:
  env: 
    APP_ENVIRONMENT_SECRET: my-dev-secret
