---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-config"
  labels: 
    {{- include "quarkus-app-chart.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
