# Default values for pipelines-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Project Coordinates
project:
  name: gitops-monorepo

application:
  name: sample-app

# Registry

image:
  registry: image-registry.openshift-image-registry.svc:5000
  group: gitops-monorepo-cicd
  name: sample-app

# Nexus Settings

nexus:
  user: admin
  pass: admin123
  url: http://sonatype-nexus-service:8081

# SonarQube Settings

sonarqube:
  user: admin
  pass: admin123
  url: http://sonarqube-sonarqube:9000

# Git Credentials

git:
  user: TO_BE_DEFINED
  token: TO_BE_DEFINED
  base_url: github.com
  full_url: https://github.com
  webhook:
    secret: s3cr3t
