# Default values for pipelines-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Project Coordinates
project:
  name: gitops-monorepo

application:
  frontend: sample-frontend
  backend: sample-backend

# Registry

image:
  registry: image-registry.openshift-image-registry.svc:5000
  group: gitops-monorepo-cicd

# Nexus Settings

nexus:
  user: admin
  pass: admin123
  url: http://sonatype-nexus-service:8081

# SonarQube Settings

sonarqube:
  user: admin
  pass: admin123
  url: http://sonarqube-sonarqube:9000

# Git Credentials

git:
  webhook:
    secret: s3cr3t
  secrets: {}
    #- name: github
    #  type: Opaque
    #  labels:
    #    credential.sync.jenkins.openshift.io: "true"
    #    sealedsecrets.bitnami.com/managed: "true"
    #  data:
    #    config: YOUR_SEALED_SECRETS_ENCRYPTED_DATA_VALUE
    #    credentials: YOUR_SEALED_SECRETS_ENCRYPTED_DATA_VALUE
