---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: gitops-monorepo-cicd
  labels:
    component-family: tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-monorepo-tools
  source:
    repoURL: https://redhat-cop.github.io/helm-charts
    chart: sonatype-nexus
    targetRevision: 1.1.3
    helm:
      values: |-
        nexus:
          resources:
            requests:
              cpu: "1"
              memory: "2048Mi"
            limits:
              cpu: "2"
              memory: "2048Mi"
  destination:
    namespace: gitops-monorepo-cicd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
