{{- if .Values.envFrom.configmap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-config-env"
  labels: 
    {{- include "node-app-chart.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end -}}
