---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ .Values.name | quote }}
  labels:
    {{- include "node-app-chart.labels" . | nindent 4 }}
spec:
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    app: {{ .Values.name | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-config.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      labels:
      {{- include "node-app-chart.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.name | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          {{- if or (.Values.envFrom.configmap.enabled) (.Values.envFrom.secrets.enabled) }}
          envFrom:
            {{- if .Values.envFrom.configmap.enabled }}
            - configMapRef:
                name: "{{ .Values.name }}-config-env"
            {{- end }}
            {{- if .Values.envFrom.secrets.enabled }}
            - secretRef:
                name: "{{ .Values.name }}-config-env-secret"
            {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 9779
              protocol: TCP
            - name: jolokia
              containerPort: 8778
              protocol: TCP
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}/{{ .Values.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmpfs-var
              mountPath: /var/run
            - name: tmpfs-var-nginx-cache
              mountPath: /var/cache/nginx
            {{- if .Values.config.enabled }}
            - name: config
              mountPath: /usr/share/nginx/html/assets/config            
            {{- end }}
      volumes:
        - name: tmpfs-var
          emptyDir: {}
        - name: tmpfs-var-nginx-cache
          emptyDir: {}
        {{- if .Values.config.enabled }}          
        - name: config
          configMap:
            name: {{ .Values.name }}-config
            defaultMode: 420
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
