---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-config-secret"
  labels: 
    {{- include "node-app-chart.labels" . | nindent 4 }}
type: "Opaque"
stringData:
{{- range $k, $v := .Values.secrets.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
