apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: gitops-monorepo-cicd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: gitops-monorepo-tools
  source:
    repoURL: https://redhat-cop.github.io/helm-charts
    chart: sonarqube
    targetRevision: 0.1.0
    helm:
      parameters:
        - name: initContainers
          value: 'true'
      values: |-
        account:
          username: "admin"
          password: "admin123"
          currentAdminPassword: "admin"
        plugins:
          install:
            - "https://github.com/checkstyle/sonar-checkstyle/releases/download/9.2/checkstyle-sonar-plugin-9.2.jar"
            - "https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar"
  destination:
    namespace: gitops-monorepo-cicd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
