# Values to apply in Production Environment

name: "sample-frontend"
nameOverride: "sample-frontend"

# Application Deployment

replicaCount: 1

image:
  tag: "latest"

# Config
config:
  enabled: true
  values:
    backendServiceUrl: https://sample-backend-gitops-monorepo-pro.apps.labs.sandbox893.opentlc.com
    environment: pro
