# Values to apply in Integration Environment

name: "sample-app"
nameOverride: "sample-app"

# Application Deployment

replicaCount: 1

image:
  tag: "1.0.3-20220322-083404-57b7af4"

# Config
config:
  env:
    APP_ENVIRONMENT: "int"
    CHAOS_READINESS_ENABLE: "false"
    CHAOS_READINESS_CRON: "0 */2 * * * ?"
    CHAOS_LIVENESS_ENABLE: "false"
    CHAOS_LIVENESS_CRON: "0 */2 * * * ?"

# Secrets
secrets:
  env: 
    APP_ENVIRONMENT_SECRET: my-int-secret
